# Generated by Django 4.1.7 on 2023-03-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image_url',
            field=models.URLField(),
        ),
    ]
