# Generated by Django 4.1.7 on 2023-03-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_shoe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
