# Generated by Django 4.2.9 on 2024-02-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_shoe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
